<?php
declare(strict_types=1);

use Magento\Backend\Block\Template;
use Magento\Framework\Escaper;

/** @var Template $block */
/** @var Escaper $escaper */

$fieldName = $block->getData('fieldName');
$parameterName = $block->getData('parameterName');
$htmlId = $block->getData('htmlId');
$htmlName = $block->getData('htmlName');
$fieldData = $block->getData('fieldData');
$isModal = $block->getData('isModal');
$isRequired = isset($fieldData['required']) && $fieldData['required'];
$additionalData = $block->getData('additionalData');
?>
<div class="mageos-wysiwyg-editor">
    <button type="button" class="scalable action-show-hide" id="<?= $isModal ? 'modal_' : '' ?>toggle_<?= /** @noEscape */ "wysiwyg_{$htmlId}_{$fieldName}_<%- data.index %>"; ?>">
        <span><?= __('Show / Hide Editor') ?></span>
    </button>
    <textarea data-field="<?= /** @noEscape */ $fieldName; ?>"
    <?php if ($isModal): ?>
        id="<?= /** @noEscape */ "edit_wysiwyg_{$htmlId}_{$fieldName}_<%- data.index %>"; ?>"
        data-name="parameters[<?= $parameterName; ?>][<%- data.index %>][<?= /** @noEscape */ $fieldName; ?>]"
    <?php else: ?>
        id="<?= /** @noEscape */ "wysiwyg_{$htmlId}_{$fieldName}_<%- data.index %>"; ?>"
    <?php endif; ?>
        data-type="<?= /** @noEscape */ $fieldData['type'] ?>"
              value="<%- data.<?= $fieldName; ?> %>"
              name="<?= /** @noEscape */ $htmlName; ?>[<%- data.index %>][<?= /** @noEscape */ $fieldName; ?>]"
    <?php if ($isRequired): ?>
        aria-invalid="false"
    <?php endif; ?>
        class="widget-option input-wysiwyg admin__control-text <?php if ($isRequired): ?>required-entry _required valid<?php endif; ?>"><%- data.<?= /** @noEscape */ $fieldName; ?> %></textarea>
</div>
